(function(BJ){
'use strict';
BJ.Game.prototype.rankValue = function(r){return r==='A'?11:r==='10'?10:Number(r)};
BJ.Game.prototype.randomRank = function(){const x=Math.floor(Math.random()*13);return x===0?'A':x>=9?'10':String(x+1)};
BJ.Game.prototype.virtualValue = function(cards){let total=0,aces=0;for(const r of cards){if(r==='A'){total+=11;aces++}else total+=this.rankValue(r)}while(total>21&&aces){total-=10;aces--}return{total,soft:aces>0}};
BJ.Game.prototype.virtualRecommend = function(cards,dealerUp,canDouble=true,canSplit=true,fromSplit=false){const d=this.rankValue(dealerUp),v=this.virtualValue(cards),total=v.total,soft=v.soft;if(cards.length===2&&canSplit&&cards[0]===cards[1]){const p=cards[0];if(['A','8'].includes(p))return'split';if(p==='10')return'stand';if(p==='9')return[2,3,4,5,6,8,9].includes(d)?'split':'stand';if(p==='7')return[2,3,4,5,6,7].includes(d)?'split':'hit';if(p==='6')return[2,3,4,5,6].includes(d)?'split':'hit';if(p==='5')return[2,3,4,5,6,7,8,9].includes(d)&&canDouble?'double':'hit';if(p==='4')return[5,6].includes(d)?'split':'hit';if(['2','3'].includes(p))return[2,3,4,5,6,7].includes(d)?'split':'hit'}if(cards.length===2&&!fromSplit&&!soft){if(total===16&&[9,10,11].includes(d))return'surrender';if(total===15&&d===10)return'surrender'}if(soft){if(total>=19)return'stand';if(total===18){if([3,4,5,6].includes(d)&&canDouble)return'double';if([2,7,8].includes(d))return'stand';return'hit'}if(total===17)return[3,4,5,6].includes(d)&&canDouble?'double':'hit';if([15,16].includes(total))return[4,5,6].includes(d)&&canDouble?'double':'hit';if([13,14].includes(total))return[5,6].includes(d)&&canDouble?'double':'hit'}if(total>=17)return'stand';if([13,14,15,16].includes(total))return[2,3,4,5,6].includes(d)?'stand':'hit';if(total===12)return[4,5,6].includes(d)?'stand':'hit';if(total===11)return canDouble?'double':'hit';if(total===10)return[2,3,4,5,6,7,8,9].includes(d)&&canDouble?'double':'hit';if(total===9)return[3,4,5,6].includes(d)&&canDouble?'double':'hit';return'hit'};
BJ.Game.prototype.simulateDealer = function(up){const cards=[up,this.randomRank()];while(true){const v=this.virtualValue(cards);if(v.total>17||v.total===17)return v.total;cards.push(this.randomRank())}};
BJ.Game.prototype.simulateOneHand = function(startCards,dealerUp,forcedAction=null,fromSplit=false){let cards=[...startCards],action=forcedAction,stake=1;while(true){const v=this.virtualValue(cards);if(v.total>21)return{result:'loss',ev:-stake};if(!action)action=this.virtualRecommend(cards,dealerUp,cards.length===2,true,fromSplit);if(action==='surrender')return{result:'loss',ev:-0.5};if(action==='double'){stake=2;cards.push(this.randomRank());const pv=this.virtualValue(cards).total;if(pv>21)return{result:'loss',ev:-2};const dv=this.simulateDealer(dealerUp);if(dv>21||pv>dv)return{result:'win',ev:2};if(pv===dv)return{result:'push',ev:0};return{result:'loss',ev:-2}}if(action==='hit'){cards.push(this.randomRank());action=null;continue}if(action==='stand'){const pv=v.total,dv=this.simulateDealer(dealerUp);if(dv>21||pv>dv)return{result:'win',ev:stake};if(pv===dv)return{result:'push',ev:0};return{result:'loss',ev:-stake}}if(action==='split'){const rank=cards[0];const a=this.simulateOneHand([rank,this.randomRank()],dealerUp,null,true);const b=this.simulateOneHand([rank,this.randomRank()],dealerUp,null,true);const pick=Math.random()<.5?a:b;return{result:pick.result,ev:(a.ev+b.ev)/2}}}};
BJ.Game.prototype.calculateDisplayedOdds = function(){if(!this.roundActive||this.animating||this.insurancePending||!this.dealer.length||!this.hands[this.active]||!this.hands[this.active].cards.length)return null;const ranks=this.hands[this.active].cards.map(c=>this.pairRank(c));const up=this.pairRank(this.dealer[0]);const action=this.virtualRecommend(ranks,up,ranks.length===2,true,this.hands[this.active].fromSplit);const key=ranks.join(',')+'|'+up+'|'+action;if(this.oddsCache.has(key))return this.oddsCache.get(key);const n=30000,count={win:0,push:0,loss:0},evs=[];for(let i=0;i<n;i++){const r=this.simulateOneHand(ranks,up,action,this.hands[this.active].fromSplit);count[r.result]++;evs.push(r.ev)}const out={action,win:count.win/n*100,push:count.push/n*100,loss:count.loss/n*100,ev:evs.reduce((a,b)=>a+b,0)/n};this.oddsCache.set(key,out);return out};
BJ.Game.prototype.renderOdds = function(){const box=BJ.$('oddsBox');if(!BJ.$('showOdds').checked){box.classList.remove('show');return}const current=this.calculateDisplayedOdds();if(current)this.lastDisplayedOdds=current;const o=current||this.lastDisplayedOdds;if(!o){box.classList.remove('show');return}box.classList.add('show');BJ.$('oddsTitle').textContent='סיכויים לפי היד המוצגת';BJ.$('oddsWin').textContent=o.win.toFixed(1)+'%';BJ.$('oddsPush').textContent=o.push.toFixed(1)+'%';BJ.$('oddsLoss').textContent=o.loss.toFixed(1)+'%';BJ.$('oddsNote').textContent='חישוב משוער לפי היד המוצגת וקלף הדילר בלבד, ללא התחשבות בקלפים שיצאו מהנעל. EV משוער: '+(o.ev>=0?'+':'')+o.ev.toFixed(3)+' יחידות הימור.'};
})(window.BJ);