(function(BJ){
'use strict';
BJ.Game.prototype.addHistory = function(text){this.history.unshift({round:this.stats.rounds,text,bank:this.bank});this.history=this.history.slice(0,10)};
BJ.Game.prototype.cardHTML = function(c,animated=false){const r=this.rank(c),s=c.slice(-1),red=['♥','♦'].includes(s)?' red':'';return'<div class="card-wrap'+(animated?' deal-animate':'')+'"><div class="card-inner"><div class="card-face card-front'+red+'"><span>'+r+s+'</span><span style="align-self:flex-end">'+s+'</span></div><div class="card-face card-back"></div></div></div>'};
BJ.Game.prototype.render = function(msg){this.stats=this.stats||{};for(const key of ['rounds','hands','wins','losses','pushes','blackjacks','busts','correct','decisions'])if(!Number.isFinite(Number(this.stats[key])))this.stats[key]=0;if(!Number.isFinite(Number(this.sessionStartBank)))this.sessionStartBank=400;const money=n=>Number(n).toFixed(1).replace('.0','')+' ₪';const profit=this.bank-this.sessionStartBank;BJ.$('bank').textContent=money(this.bank);BJ.$('profitLoss').textContent=(profit>0?'+':'')+money(profit);BJ.$('profitLoss').classList.toggle('positive',profit>0);BJ.$('profitLoss').classList.toggle('negative',profit<0);BJ.$('profitLoss').classList.toggle('neutral',profit===0);BJ.$('handsPlayed').textContent=this.stats.hands;BJ.$('wins').textContent=this.stats.wins;BJ.$('losses').textContent=this.stats.losses;BJ.$('pushes').textContent=this.stats.pushes;const rc=this.runningCount||0,tc=this.trueCount(),dr=this.shoe.length/52;BJ.$('runningCount').textContent=(rc>0?'+':'')+rc;BJ.$('trueCount').textContent=(tc>0?'+':'')+tc.toFixed(1);BJ.$('decksRemaining').textContent=dr.toFixed(1);for(const el of [BJ.$('runningCount'),BJ.$('trueCount')]){el.classList.remove('positive','negative','neutral');el.classList.add(Number(el.textContent)>0?'positive':Number(el.textContent)<0?'negative':'neutral');}const showRecommendation=this.roundActive&&!this.insurancePending&&!this.animating&&BJ.$('showHint').checked&&this.dealer.length>0&&this.hands[this.active]&&this.hands[this.active].cards.length>=2;BJ.$('message').innerHTML=msg||'';BJ.$('dealerCards').innerHTML=this.dealer.map((c,i)=>this.cardHTML(c,this.animatedCards.has('dealer:'+i))).join('');if(!this.dealer.length){
  BJ.$('dealerTotal').textContent='';
}else{
  // בזמן החלטות השחקן מוצג רק הקלף הגלוי. מרגע שהדילר מתחיל
  // למשוך, הסכום המלא מתעדכן לאחר כל קלף שנחשף.
  const dealerDrawing=this.dealer.length>1;
  const dealerValue=dealerDrawing?this.value(this.dealer):this.value([this.dealer[0]]);
  const dealerLabel=dealerValue.total>21?'Bust '+dealerValue.total:(dealerValue.soft?'Soft ':'')+dealerValue.total;
  BJ.$('dealerTotal').textContent='('+dealerLabel+')';
}let html='';this.hands.forEach((h,i)=>{const v=this.value(h.cards);const recommendation=showRecommendation&&i===this.active?'<span class="player-recommendation">המלצה: '+this.recommend().toUpperCase()+'</span>':'';html+='<div class="hand '+(this.roundActive&&i===this.active?'active':'')+'"><div class="handhead"><b>יד '+(i+1)+' — '+(v.soft?'Soft ':'')+v.total+' '+recommendation+'</b><span>'+h.bet+' ₪ '+(h.result?'• '+h.result:'')+'</span></div><div class="cards">'+h.cards.map((c,j)=>this.cardHTML(c,this.animatedCards.has('hand:'+i+':'+j))).join('')+'</div></div>'});BJ.$('playerHands').innerHTML=html;const a=this.actions();BJ.$('hitBtn').disabled=!a.includes('hit');BJ.$('standBtn').disabled=!a.includes('stand');BJ.$('doubleBtn').disabled=!a.includes('double');BJ.$('splitBtn').disabled=!a.includes('split');BJ.$('surrenderBtn').disabled=!a.includes('surrender');BJ.$('newBtn').disabled=this.roundActive||this.animating;BJ.$('insuranceBtn').disabled=!this.insurancePending;BJ.$('noInsuranceBtn').disabled=!this.insurancePending;BJ.$('history').innerHTML=this.history.map(x=>'<div class="historyitem"><b>סיבוב '+x.round+'</b><br>'+x.text+'<br><span class="muted">בנק: '+x.bank.toFixed(1).replace('.0','')+' ₪</span></div>').join('')||'<span class="muted">אין היסטוריה.</span>';this.renderOdds()};
})(window.BJ);