// Strategy engine v3: corrected soft-hand detection (Ace counted as 11).
(function(){
'use strict';
function $(id){return document.getElementById(id)}
let shuffleNoticeTimer=null;
function showShuffleNotice(){const o=$('shuffleOverlay');if(!o)return;clearTimeout(shuffleNoticeTimer);o.classList.add('show');o.setAttribute('aria-hidden','false');shuffleNoticeTimer=setTimeout(()=>{o.classList.remove('show');o.setAttribute('aria-hidden','true')},2200)}
class Game{
 constructor(){this.animating=false;this.animatedCards=new Set();this.oddsCache=new Map();this.lastDisplayedOdds=null;this.reset()}
 reset(){this.animating=false;this.animatedCards=new Set();this.bank=400;this.stats={rounds:0,wins:0,losses:0,pushes:0,correct:0,decisions:0};this.hands=[];this.dealer=[];this.active=0;this.roundActive=false;this.insurancePending=false;this.insuranceBet=0;this.history=[];this.makeShoe();this.render('לחצי על “חלוקה חדשה” כדי להתחיל.')}
 makeShoe(){this.runningCount=0;const n=Number($('decks').value||5),r=['A','2','3','4','5','6','7','8','9','10','J','Q','K'],s=['♠','♥','♦','♣'];this.shoe=[];for(let d=0;d<n;d++)for(const suit of s)for(const rank of r)this.shoe.push(rank+suit);for(let i=this.shoe.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));const t=this.shoe[i];this.shoe[i]=this.shoe[j];this.shoe[j]=t}}
 draw(){if(!this.shoe.length){this.makeShoe();showShuffleNotice()}return this.shoe.pop()}
 hiLoValue(c){const r=this.rank(c);if(['2','3','4','5','6'].includes(r))return 1;if(['10','J','Q','K','A'].includes(r))return -1;return 0}
 countRevealedCard(c){this.runningCount=(this.runningCount||0)+this.hiLoValue(c)}
 trueCount(){const decksRemaining=Math.max(this.shoe.length/52,0.25);return (this.runningCount||0)/decksRemaining}
 rank(c){return c.slice(0,-1)}
 pairRank(c){const r=this.rank(c);return ['10','J','Q','K'].includes(r)?'10':r}
 value(cards){let total=0,aces=0;for(const c of cards){const r=this.rank(c);if(r==='A'){total+=11;aces++}else if(['J','Q','K'].includes(r))total+=10;else total+=Number(r)}while(total>21&&aces>0){total-=10;aces--}const soft=aces>0;return{total,soft}}
 isBJ(h){return h.cards.length===2&&this.value(h.cards).total===21&&!h.fromSplit}
 async start(){if(this.roundActive||this.animating)return;this.lastDisplayedOdds=null;const bet=Number($('bet').value);if(this.bank<bet){this.render('אין מספיק כסף להימור.');return}if(!$('disableCutCard').checked&&this.shoe.length<=130){this.makeShoe();showShuffleNotice();}this.hands=[{cards:[],bet,fromSplit:false,done:false,result:null}];this.dealer=[];this.active=0;this.roundActive=true;this.insurancePending=false;this.insuranceBet=0;this.stats.rounds++;this.animating=true;this.render('הקלפים מחולקים…');
   await this.dealCard('hand',0);await this.dealCard('dealer');await this.dealCard('hand',0);this.animating=false;this.insurancePending=this.rank(this.dealer[0])==='A';
   if(this.isBJ(this.hands[0])&&!['A','10'].includes(this.pairRank(this.dealer[0]))){const h=this.hands[0];this.bank+=h.bet*1.5;h.done=true;h.result='Blackjack';this.stats.wins++;this.roundActive=false;this.addHistory('Blackjack טבעי — ניצחון 3:2');this.render('🃏 Blackjack טבעי!');return}
   this.render(this.insurancePending?'לדילר יש אס. בחרי Insurance או ללא Insurance.':'בחרי מהלך.')}
 actions(){if(!this.roundActive||this.insurancePending||this.animating)return[];const h=this.hands[this.active],t=this.value(h.cards).total;let a=['hit','stand'];if(h.cards.length===2&&this.bank>=h.bet)a.push('double');if(h.cards.length===2&&this.pairRank(h.cards[0])===this.pairRank(h.cards[1])&&this.hands.length<4&&this.bank>=h.bet)a.push('split');if(this.hands.length===1&&h.cards.length===2&&!h.fromSplit)a.push('surrender');if(t>=21)a=['stand'];return a}
 recommend(){const h=this.hands[this.active];if(!h||!h.cards||h.cards.length<2||!this.dealer.length)return'hit';const dv=this.pairRank(this.dealer[0]),d=dv==='A'?11:dv==='10'?10:Number(dv),v=this.value(h.cards),total=v.total,soft=v.soft;if(h.cards.length===2&&this.pairRank(h.cards[0])===this.pairRank(h.cards[1])){const p=this.pairRank(h.cards[0]);if(['A','8'].includes(p))return'split';if(p==='10')return'stand';if(p==='9')return[2,3,4,5,6,8,9].includes(d)?'split':'stand';if(p==='7')return[2,3,4,5,6,7].includes(d)?'split':'hit';if(p==='6')return[2,3,4,5,6].includes(d)?'split':'hit';if(p==='5')return[2,3,4,5,6,7,8,9].includes(d)?'double':'hit';if(p==='4')return[5,6].includes(d)?'split':'hit';if(['2','3'].includes(p))return[2,3,4,5,6,7].includes(d)?'split':'hit'}if(h.cards.length===2&&!h.fromSplit){if(total===16&&[9,10,11].includes(d))return'surrender';if(total===15&&d===10)return'surrender'}if(soft){if(total>=19)return'stand';if(total===18){if([3,4,5,6].includes(d)&&this.actions().includes('double'))return'double';if([2,7,8].includes(d))return'stand';return'hit'}if(total===17)return[3,4,5,6].includes(d)&&this.actions().includes('double')?'double':'hit';if([15,16].includes(total))return[4,5,6].includes(d)&&this.actions().includes('double')?'double':'hit';if([13,14].includes(total))return[5,6].includes(d)&&this.actions().includes('double')?'double':'hit'}if(total>=17)return'stand';if([13,14,15,16].includes(total))return[2,3,4,5,6].includes(d)?'stand':'hit';if(total===12)return[4,5,6].includes(d)?'stand':'hit';if(total===11)return this.actions().includes('double')?'double':'hit';if(total===10)return[2,3,4,5,6,7,8,9].includes(d)&&this.actions().includes('double')?'double':'hit';if(total===9)return[3,4,5,6].includes(d)&&this.actions().includes('double')?'double':'hit';return'hit'}

 rankValue(r){return r==='A'?11:r==='10'?10:Number(r)}
 randomRank(){const x=Math.floor(Math.random()*13);return x===0?'A':x>=9?'10':String(x+1)}
 virtualValue(cards){let total=0,aces=0;for(const r of cards){if(r==='A'){total+=11;aces++}else total+=this.rankValue(r)}while(total>21&&aces){total-=10;aces--}return{total,soft:aces>0}}
 virtualRecommend(cards,dealerUp,canDouble=true,canSplit=true,fromSplit=false){const d=this.rankValue(dealerUp),v=this.virtualValue(cards),total=v.total,soft=v.soft;if(cards.length===2&&canSplit&&cards[0]===cards[1]){const p=cards[0];if(['A','8'].includes(p))return'split';if(p==='10')return'stand';if(p==='9')return[2,3,4,5,6,8,9].includes(d)?'split':'stand';if(p==='7')return[2,3,4,5,6,7].includes(d)?'split':'hit';if(p==='6')return[2,3,4,5,6].includes(d)?'split':'hit';if(p==='5')return[2,3,4,5,6,7,8,9].includes(d)&&canDouble?'double':'hit';if(p==='4')return[5,6].includes(d)?'split':'hit';if(['2','3'].includes(p))return[2,3,4,5,6,7].includes(d)?'split':'hit'}if(cards.length===2&&!fromSplit){if(total===16&&[9,10,11].includes(d))return'surrender';if(total===15&&d===10)return'surrender'}if(soft){if(total>=19)return'stand';if(total===18){if([3,4,5,6].includes(d)&&canDouble)return'double';if([2,7,8].includes(d))return'stand';return'hit'}if(total===17)return[3,4,5,6].includes(d)&&canDouble?'double':'hit';if([15,16].includes(total))return[4,5,6].includes(d)&&canDouble?'double':'hit';if([13,14].includes(total))return[5,6].includes(d)&&canDouble?'double':'hit'}if(total>=17)return'stand';if([13,14,15,16].includes(total))return[2,3,4,5,6].includes(d)?'stand':'hit';if(total===12)return[4,5,6].includes(d)?'stand':'hit';if(total===11)return canDouble?'double':'hit';if(total===10)return[2,3,4,5,6,7,8,9].includes(d)&&canDouble?'double':'hit';if(total===9)return[3,4,5,6].includes(d)&&canDouble?'double':'hit';return'hit'}
 simulateDealer(up){const cards=[up,this.randomRank()];while(true){const v=this.virtualValue(cards);if(v.total>17||v.total===17)return v.total;cards.push(this.randomRank())}}
 simulateOneHand(startCards,dealerUp,forcedAction=null,fromSplit=false){let cards=[...startCards],action=forcedAction,stake=1;while(true){const v=this.virtualValue(cards);if(v.total>21)return{result:'loss',ev:-stake};if(!action)action=this.virtualRecommend(cards,dealerUp,cards.length===2,true,fromSplit);if(action==='surrender')return{result:'loss',ev:-0.5};if(action==='double'){stake=2;cards.push(this.randomRank());const pv=this.virtualValue(cards).total;if(pv>21)return{result:'loss',ev:-2};const dv=this.simulateDealer(dealerUp);if(dv>21||pv>dv)return{result:'win',ev:2};if(pv===dv)return{result:'push',ev:0};return{result:'loss',ev:-2}}if(action==='hit'){cards.push(this.randomRank());action=null;continue}if(action==='stand'){const pv=v.total,dv=this.simulateDealer(dealerUp);if(dv>21||pv>dv)return{result:'win',ev:stake};if(pv===dv)return{result:'push',ev:0};return{result:'loss',ev:-stake}}if(action==='split'){const rank=cards[0];const a=this.simulateOneHand([rank,this.randomRank()],dealerUp,null,true);const b=this.simulateOneHand([rank,this.randomRank()],dealerUp,null,true);const pick=Math.random()<.5?a:b;return{result:pick.result,ev:(a.ev+b.ev)/2}}}}
 calculateDisplayedOdds(){if(!this.roundActive||this.animating||this.insurancePending||!this.dealer.length||!this.hands[this.active]||!this.hands[this.active].cards.length)return null;const ranks=this.hands[this.active].cards.map(c=>this.pairRank(c));const up=this.pairRank(this.dealer[0]);const action=this.virtualRecommend(ranks,up,ranks.length===2,true,this.hands[this.active].fromSplit);const key=ranks.join(',')+'|'+up+'|'+action;if(this.oddsCache.has(key))return this.oddsCache.get(key);const n=30000,count={win:0,push:0,loss:0},evs=[];for(let i=0;i<n;i++){const r=this.simulateOneHand(ranks,up,action,this.hands[this.active].fromSplit);count[r.result]++;evs.push(r.ev)}const out={action,win:count.win/n*100,push:count.push/n*100,loss:count.loss/n*100,ev:evs.reduce((a,b)=>a+b,0)/n};this.oddsCache.set(key,out);return out}
 renderOdds(){const box=$('oddsBox');if(!$('showOdds').checked){box.classList.remove('show');return}const current=this.calculateDisplayedOdds();if(current)this.lastDisplayedOdds=current;const o=current||this.lastDisplayedOdds;if(!o){box.classList.remove('show');return}box.classList.add('show');$('oddsTitle').textContent='סיכויים לפי היד המוצגת';$('oddsWin').textContent=o.win.toFixed(1)+'%';$('oddsPush').textContent=o.push.toFixed(1)+'%';$('oddsLoss').textContent=o.loss.toFixed(1)+'%';$('oddsNote').textContent='חישוב משוער לפי היד המוצגת וקלף הדילר בלבד, ללא התחשבות בקלפים שיצאו מהנעל. EV משוער: '+(o.ev>=0?'+':'')+o.ev.toFixed(3)+' יחידות הימור.'}
 async dealCard(target,handIndex=0){const card=this.draw();let key;if(target==='dealer'){this.dealer.push(card);key='dealer:'+(this.dealer.length-1)}else{this.hands[handIndex].cards.push(card);key='hand:'+handIndex+':'+(this.hands[handIndex].cards.length-1)}this.animatedCards.add(key);this.render('קלף נמשך…');await new Promise(r=>setTimeout(r,980));this.animatedCards.delete(key);this.countRevealedCard(card);return card}
 async act(action){if(this.animating||!this.actions().includes(action))return;const rec=this.recommend();this.stats.decisions++;const correct=action===rec;if(correct)this.stats.correct++;let note=correct?'<span class="good">✅ החלטה נכונה.</span>':'<span class="bad">❌ עדיף: '+rec.toUpperCase()+'</span>';const h=this.hands[this.active];this.animating=true;
   if(action==='hit'){await this.dealCard('hand',this.active);const t=this.value(h.cards).total;if(t>21){h.done=true;h.result='Bust';note+='<br><span class="bad">עברת 21 — הפסד אוטומטי.</span>';await this.advance()}else if(t===21){h.done=true;await this.advance()}}
   else if(action==='stand'){h.done=true;await this.advance()}
   else if(action==='double'){h.bet*=2;await this.dealCard('hand',this.active);h.done=true;if(this.value(h.cards).total>21)h.result='Bust';await this.advance()}
   else if(action==='surrender'){h.done=true;h.result='surrender';await this.advance()}
   else if(action==='split'){const a=h.cards[0],b=h.cards[1];this.hands.splice(this.active,1,{cards:[a],bet:h.bet,fromSplit:true,done:false,result:null},{cards:[b],bet:h.bet,fromSplit:true,done:false,result:null});await this.dealCard('hand',this.active);await this.dealCard('hand',this.active+1)}
   this.animating=false;this.render(note)}
 async advance(){for(let i=this.active+1;i<this.hands.length;i++){if(!this.hands[i].done){this.active=i;return}}await this.settle()}
 async settle(){const live=this.hands.some(h=>h.result!=='surrender'&&this.value(h.cards).total<=21);if(live){await this.dealCard('dealer');const dbj=this.dealer.length===2&&this.value(this.dealer).total===21;if(!dbj)while(this.value(this.dealer).total<17)await this.dealCard('dealer')}const dt=this.value(this.dealer).total,dbj=this.dealer.length===2&&dt===21;texts=[];if(this.insuranceBet>0){if(dbj){this.bank+=this.insuranceBet*2;texts.push('Insurance זכה')}else{this.bank-=this.insuranceBet;texts.push('Insurance הפסיד')}}for(const h of this.hands){const pt=this.value(h.cards).total,pbj=this.isBJ(h);if(h.result==='surrender'){this.bank-=h.bet/2;this.stats.losses++;h.result='Surrender';texts.push('Surrender');continue}if(pt>21||h.result==='Bust'){this.bank-=h.bet;this.stats.losses++;h.result='Bust';texts.push('Bust');continue}if(dbj){if(pbj){this.stats.pushes++;h.result='Push'}else{this.bank-=h.bet;this.stats.losses++;h.result='Dealer Blackjack'}texts.push(h.result);continue}if(pbj){this.bank+=h.bet*1.5;this.stats.wins++;h.result='Blackjack'}else if(dt>21||pt>dt){this.bank+=h.bet;this.stats.wins++;h.result='Win'}else if(pt<dt){this.bank-=h.bet;this.stats.losses++;h.result='Loss'}else{this.stats.pushes++;h.result='Push'}texts.push(h.result)}this.roundActive=false;this.addHistory(texts.join(' • '));this.render('הסיבוב הסתיים.')}
 takeInsurance(){if(!this.insurancePending)return;this.insuranceBet=this.hands[0].bet/2;this.insurancePending=false;this.render('Insurance נלקח.')}
 declineInsurance(){if(!this.insurancePending)return;this.insurancePending=false;this.render('ממשיכים ללא Insurance.')}
 addHistory(text){this.history.unshift({round:this.stats.rounds,text,bank:this.bank});this.history=this.history.slice(0,10)}
 cardHTML(c,animated=false){const r=this.rank(c),s=c.slice(-1),red=['♥','♦'].includes(s)?' red':'';return'<div class="card-wrap'+(animated?' deal-animate':'')+'"><div class="card-inner"><div class="card-face card-front'+red+'"><span>'+r+s+'</span><span style="align-self:flex-end">'+s+'</span></div><div class="card-face card-back"></div></div></div>'}
 render(msg){$('bank').textContent=this.bank.toFixed(1).replace('.0','')+' ₪';$('rounds').textContent=this.stats.rounds;$('wins').textContent=this.stats.wins;$('losses').textContent=this.stats.losses;$('remaining').textContent=this.shoe.length;$('accuracy').textContent=(this.stats.decisions?Math.round(this.stats.correct/this.stats.decisions*100):100)+'%';const rc=this.runningCount||0,tc=this.trueCount(),dr=this.shoe.length/52;$('runningCount').textContent=(rc>0?'+':'')+rc;$('trueCount').textContent=(tc>0?'+':'')+tc.toFixed(1);$('decksRemaining').textContent=dr.toFixed(1);for(const el of [$('runningCount'),$('trueCount')]){el.classList.remove('positive','negative','neutral');el.classList.add(Number(el.textContent)>0?'positive':Number(el.textContent)<0?'negative':'neutral');}if(this.roundActive&&!this.insurancePending&&!this.animating&&$('showHint').checked&&this.dealer.length>0&&this.hands[this.active]&&this.hands[this.active].cards.length>=2)msg+=(msg?'<br>':'')+'המלצה: '+this.recommend().toUpperCase();$('message').innerHTML=msg||'';$('dealerCards').innerHTML=this.dealer.map((c,i)=>this.cardHTML(c,this.animatedCards.has('dealer:'+i))).join('');$('dealerTotal').textContent=this.dealer.length?(this.roundActive?'('+this.value([this.dealer[0]]).total+')':'('+this.value(this.dealer).total+')'):'';let html='';this.hands.forEach((h,i)=>{const v=this.value(h.cards);html+='<div class="hand '+(this.roundActive&&i===this.active?'active':'')+'"><div class="handhead"><b>יד '+(i+1)+' — '+(v.soft?'Soft ':'')+v.total+'</b><span>'+h.bet+' ₪ '+(h.result?'• '+h.result:'')+'</span></div><div class="cards">'+h.cards.map((c,j)=>this.cardHTML(c,this.animatedCards.has('hand:'+i+':'+j))).join('')+'</div></div>'});$('playerHands').innerHTML=html;const a=this.actions();$('hitBtn').disabled=!a.includes('hit');$('standBtn').disabled=!a.includes('stand');$('doubleBtn').disabled=!a.includes('double');$('splitBtn').disabled=!a.includes('split');$('surrenderBtn').disabled=!a.includes('surrender');$('newBtn').disabled=this.roundActive||this.animating;$('insuranceBtn').disabled=!this.insurancePending;$('noInsuranceBtn').disabled=!this.insurancePending;$('history').innerHTML=this.history.map(x=>'<div class="historyitem"><b>סיבוב '+x.round+'</b><br>'+x.text+'<br><span class="muted">בנק: '+x.bank.toFixed(1).replace('.0','')+' ₪</span></div>').join('')||'<span class="muted">אין היסטוריה.</span>';this.renderOdds()}
 save(){const data={bank:this.bank,stats:this.stats,hands:this.hands,dealer:this.dealer,active:this.active,roundActive:this.roundActive,insurancePending:this.insurancePending,insuranceBet:this.insuranceBet,history:this.history,shoe:this.shoe,runningCount:this.runningCount};localStorage.setItem('bjIphoneFixed',JSON.stringify(data));this.render('המשחק נשמר.')}
 load(){const raw=localStorage.getItem('bjIphoneFixed');if(!raw){this.render('לא נמצא משחק שמור.');return}Object.assign(this,JSON.parse(raw));this.render('המשחק נטען.')}
}
let texts=[];

function updateCountVisibility(){
  const box=$('countBox');
  const toggle=$('showCount');
  if(!box||!toggle)return;
  box.classList.toggle('hidden',!toggle.checked);
  localStorage.setItem('bjShowCount',toggle.checked?'1':'0');
}

function updateCutCardSetting(){
  const toggle=$('disableCutCard');
  if(!toggle)return;
  localStorage.setItem('bjDisableCutCard',toggle.checked?'1':'0');
}

const game=new Game();
$('newBtn').addEventListener('click',()=>game.start());
$('hitBtn').addEventListener('click',()=>game.act('hit'));
$('standBtn').addEventListener('click',()=>game.act('stand'));
$('doubleBtn').addEventListener('click',()=>game.act('double'));
$('splitBtn').addEventListener('click',()=>game.act('split'));
$('surrenderBtn').addEventListener('click',()=>game.act('surrender'));
$('insuranceBtn').addEventListener('click',()=>game.takeInsurance());
$('noInsuranceBtn').addEventListener('click',()=>game.declineInsurance());
$('saveBtn').addEventListener('click',()=>game.save());
$('loadBtn').addEventListener('click',()=>game.load());
$('resetBtn').addEventListener('click',()=>game.reset());
$('decks').addEventListener('change',()=>{if(!game.roundActive){game.makeShoe();game.render('הנעל אופסה.')}});
$('showHint').addEventListener('change',()=>{if(game.roundActive&&!game.animating)game.render('בחרי מהלך.');});
$('showOdds').addEventListener('change',()=>game.render(game.roundActive?'בחרי מהלך.':'לחצי על “חלוקה חדשה” כדי להתחיל.'));
$('showCount').addEventListener('change',updateCountVisibility);
$('disableCutCard').addEventListener('change',updateCutCardSetting);
$('showCount').checked=localStorage.getItem('bjShowCount')==='1';
$('disableCutCard').checked=localStorage.getItem('bjDisableCutCard')==='1';
updateCountVisibility();
updateCutCardSetting();
})();
